#!/usr/bin/env bash
# Create an ignored local api/.env with a generated PROXY_SECRET.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
API_DIR="$ROOT/api"
ENV_EXAMPLE="$API_DIR/.env.example"
ENV_FILE="$API_DIR/.env"

if [ ! -f "$ENV_EXAMPLE" ]; then
  echo "Missing api/.env.example" >&2
  exit 1
fi

if [ -f "$ENV_FILE" ]; then
  if grep -Eq '^PROXY_SECRET=.+' "$ENV_FILE"; then
    echo "api/.env already exists and PROXY_SECRET is set"
    exit 0
  fi
  printf '\n# Generated by scripts/init_local_env.sh\n' >> "$ENV_FILE"
else
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  printf '\n# Generated by scripts/init_local_env.sh\n' >> "$ENV_FILE"
fi

secret="$("$API_DIR/venv/bin/python" -c 'import secrets; print(secrets.token_hex(32))' 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"
printf 'PROXY_SECRET=%s\n' "$secret" >> "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "Created api/.env with generated PROXY_SECRET"
echo "Fill Azure, connector, and device credentials when available. Secret value was not printed."
