#!/usr/bin/env bash
# Create or update ignored local api/.env with generated local secrets.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
API_DIR="$ROOT/api"
ENV_EXAMPLE="$API_DIR/.env.example"
ENV_FILE="$API_DIR/.env"

if [ ! -f "$ENV_EXAMPLE" ]; then
  echo "Missing api/.env.example" >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
fi

generate_secret() {
  "$API_DIR/venv/bin/python" -c 'import secrets; print(secrets.token_hex(32))' 2>/dev/null \
    || python3 -c 'import secrets; print(secrets.token_hex(32))'
}

generated=0
if ! grep -Eq '^PROXY_SECRET=.+' "$ENV_FILE"; then
  if [ "$generated" -eq 0 ]; then
    printf '\n# Generated by scripts/init_local_env.sh\n' >> "$ENV_FILE"
  fi
  printf 'PROXY_SECRET=%s\n' "$(generate_secret)" >> "$ENV_FILE"
  generated=1
fi

if ! grep -Eq '^SESSION_SECRET_KEY=.+' "$ENV_FILE"; then
  if [ "$generated" -eq 0 ]; then
    printf '\n# Generated by scripts/init_local_env.sh\n' >> "$ENV_FILE"
  fi
  printf 'SESSION_SECRET_KEY=%s\n' "$(generate_secret)" >> "$ENV_FILE"
  generated=1
fi

chmod 600 "$ENV_FILE"

if [ "$generated" -eq 0 ]; then
  echo "api/.env already exists and required local secrets are set"
else
  echo "Created or updated api/.env with generated local secrets"
fi
echo "Fill Azure, connector, and device credentials when available. Secret value was not printed."
